openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "NER API"
  description: "Named Entity Recognition API"
  contact:
    name: "NER API Team"
    email: roberto.polli@par-tec.it
servers:
  - url: "/esco/v0"
  - url: "http://localhost:8080/esco/v0"
    description: "Local server"
tags:
  - name: "skills"
    description: "Skills"
  - name: "ner"
    description: "Named Entity Recognition"
paths:
  /skills:
    get:
      operationId: "api.routes.list_skills"
      description: |-
        Return the list of skills
      tags:
        - "skills"
      parameters:
        - $ref: https://teamdigitale.github.io/openapi/master/definitions.yaml#/components/parameters/limit
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  skills:
                    type: "array"
                    maxItems: 100
                    items:
                      $ref: "#/components/schemas/Skill"
  /ner:
    post:
      operationId: "api.routes.recognize_entities"
      description: |-
        Process the received content made up of a
        "text" field and an optional "metadata" field
        and return a list of the recognized entities.
      tags:
        - "ner"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                text:
                  type: "string"
                metadata:
                  type: "object"
                  properties:
                    language:
                      type: "string"
                      enum: ["it", "en"]
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  entities:
                    type: "array"
                    items:
                      type: "string"
components:
  schemas:
    Skill:
      type: "object"
      additionalProperties: false
      properties:
        uri:
          type: "string"
        label:
          type: "string"
        description:
          type: "string"
        altLabels:
          type: "array"
          items:
            type: "string"
